name: Post to Hashnode

on:
  schedule:
    - cron: '0 5 * * *'  # Setiap hari jam 10.00 WIB
  workflow_dispatch:       # Bisa dijalankan manual

jobs:
  post-to-hashnode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo
          tools: composer

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
        working-directory: backend

      - name: Copy .env
        run: cp .env.github .env
        working-directory: backend

      - name: Generate App Key
        run: php artisan key:generate
        working-directory: backend

      - name: Run the posting script
        run: php artisan post:hashnode
        working-directory: backend
